### ISSUE TITLE
Update casbin to v2

### ISSUE THREAD

**Issue by rolandjitsu** [labstack/echo-contrib#10]
I'm having some trouble using v2 of casbin with this pacakge:
```
./api.go:88:28: cannot use ce (type *"github.com/casbin/casbin/v2".Enforcer) as type *"github.com/casbin/casbin".Enforcer in argument to "github.com/labstack/echo-contrib/casbin".Middleware
```
Would be nice to update the casbin dep to v2.

P.S. I could make a quick PR if necessary.

**Comment by vishr** [comment]
@rolandjitsu Please send a PR.
