### ISSUE TITLE
Skip /metrics on separate port doesn't skip

### ISSUE THREAD

**Issue by mkyc** [labstack/echo-contrib#119]
### Issue Description

I have something like this in my code: 

```golang
e := echo.New()

mc := echoprometheus.MiddlewareConfig{
Skipper: func(c echo.Context) bool {
	fmt.Println("lalala")
	return strings.HasPrefix(c.Path(), "/prometheus")
},
Subsystem: "integrations",
}

e.Use(echoprometheus.NewMiddlewareWithConfig(mc))

go func() {
metrics := echo.New()
metrics.GET("/prometheus", echoprometheus.NewHandler())

if err := metrics.Start(":8090"); err != nil && !errors.Is(err, http.ErrServerClosed) {
	log.Fatal(err)
}
}()
```

that is basically [serve on different port](https://echo.labstack.com/docs/middleware/prometheus#examples) and [skipping](https://echo.labstack.com/docs/middleware/prometheus#skipping-urls) examples combined. 

I don't even get Skipper called on calling `localhost:8090/prometheus`, so no `lalala` in console and `/prometheus` gets counted. 

### Checklist

- [x] Dependencies installed
- [x] No typos
- [x] Searched existing issues and docs

### Expected behaviour

`/prometheus` is not counted

### Version/commit

```
github.com/labstack/echo-contrib v0.17.1
github.com/labstack/echo/v4 v4.12.0
github.com/labstack/gommon v0.4.2
```

**Comment by mkyc** [comment]
Just to clarify I can see it only here as this metrics: `promhttp_metric_handler_requests_total{code="200"} 23` but anyways looks to me like I should see  some `lalala` ;)

**Comment by chrmang** [comment]
Hi @mkyc ,  watch at the last lines from metrics output:

```
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 1
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```

the scraping requests are counted separately. The Skipper function is only for skipping "application" requests. If you are not interested in this metric, you can maybe later drop it. Have a look [at this Grafana blog post](https://grafana.com/blog/2022/03/21/how-relabeling-in-prometheus-works/)

**Comment by mkyc** [comment]
Yeah, after longer thinking about it I think it makes perfect sense.
