### ISSUE TITLE
jeager sampling  doesn't work

### ISSUE THREAD

**Issue by alperhankendi** [labstack/echo-contrib#22]
here is my config. it seems the jeager tracer doesnt care my env.
```
JAEGER_AGENT_HOST=127.0.0.1;
JAEGER_AGENT_PORT=6831;
JAEGER_SAMPLER_PARAM=0.001;
JAEGER_SAMPLER_TYPE=const
```

**Comment by aldas** [comment]
Probably not a problem anymore.

Just a note - Jaeger docs say

https://github.com/jaegertracing/jaeger-client-go#environment-variables
> The tracer can be initialized with values coming from environment variables, if it is built from a config that was created via FromEnv(). None of the env vars are required and all of them can be overridden via direct setting of the property on the configuration object.

And this is what middleware does in `New()` 
https://github.com/labstack/echo-contrib/blob/4d116eef4725384df66e4c4d079254bc53ae2d54/jaegertracing/jaegertracing.go#L84

if middleware is NOT attached with
```go
c := jaegertracing.New(e, nil)
```
then it probably does not call `FromEnv`
