### ISSUE TITLE
Repository github.com/belogik/goes not found

### ISSUE THREAD

**Issue by 0x111** [labstack/echo-contrib#30]
Hey everyone!

I wanted to use this package today, most commonly the session part, but while running the 
```
go get github.com/labstack/echo-contrib/session
```
I get the error below:
```
➜ go get github.com/labstack/echo-contrib/session
go: finding github.com/labstack/echo-contrib/session latest
go: finding github.com/belogik/goes v0.0.0-20151229125003-e54d722c3aff
go: github.com/belogik/goes@v0.0.0-20151229125003-e54d722c3aff: git fetch -f https://github.com/belogik/goes refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/x/go/pkg/mod/cache/vcs/5b0453a6aac74c86b31f0a771f02325d031eaf6ec0f0503f1cc20852de3abb0a: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/belogik/goes/' not found
go: error loading module requirements

```
It seems that this repo is gone for good, probably someone took over the username or something like that. What is this used for or is this something related to a 3rd party package?
Or maybe if someone has this package offline cached, we could get that up somewhere.
Thanks for your help!

Edit: I found this archived web page from 2018 [https://github.com/belogik/goes/](https://web.archive.org/web/20180611015504/https://github.com/belogik/goes/)
That page says that anyone using the package, should rather use this one: [https://github.com/OwnLocal/goes](https://github.com/OwnLocal/goes).

Related https://github.com/labstack/echo/issues/1494

**Comment by 0x111** [comment]
Okay, basically we just need a new release for this to work. For the others, get the master version of this repo.

**Comment by gitu** [comment]
When using go.mod you can also quickly replace the dependency version.

    // remove after upgrading echo-contrib
    replace github.com/belogik/goes => github.com/OwnLocal/goes v1.0.0 

see also: https://github.com/OwnLocal/goes/releases/tag/v1.0.0

**Comment by shyandsy** [comment]
could u make a release to fix the problem ?

@gitu the solution doesnt work for me

**Comment by 0x111** [comment]
Well, @vishr  needs to create a new release. Let's hope that happens soon.

**Comment by vishr** [comment]
Done https://github.com/labstack/echo-contrib/releases/tag/v0.9.0, thanks for the reminder!
