### ISSUE TITLE
Duplicate error messages with prometheus middleware

### ISSUE THREAD

**Issue by Foxcool** [labstack/echo-contrib#36]
https://github.com/labstack/echo-contrib/blob/master/prometheus/prometheus.go#L379

This is where error checking and error handler is called. Then, for some reason, the function returns the same error and echo itself repeats the check and call the handler. Duplicate error responses are obtained.

**Comment by Foxcool** [comment]
Behavior added here

https://github.com/labstack/echo-contrib/pull/21

**Comment by aclowkey** [comment]
Any updates on this?

**Comment by aldas** [comment]
should be handled with https://github.com/labstack/echo-contrib/pull/56
