### ISSUE TITLE
Custom tracer for tracing-middleware

### ISSUE THREAD

**Issue by andrexus** [labstack/echo-contrib#37]
I have a configured tracer which is used for tracing grpc requests. Now I want to use the same tracer for http requests. Unfortunately there is no config option in tracing-middleware to provide an existing tracer.

**Comment by aldas** [comment]
This is old. Probably not relevant anymore.

Config has tracer field. that one is not suitable?
https://github.com/labstack/echo-contrib/blob/4d116eef4725384df66e4c4d079254bc53ae2d54/jaegertracing/jaegertracing.go#L50
