### ISSUE TITLE
Generic tracing using OpenTracing

### ISSUE THREAD

**Issue by uudashr** [labstack/echo-contrib#43]
Maybe better to support OpenTracing rather than specific to or has dependency to Jaeger

**Comment by arun0009** [comment]
@uudashr - We now have Zipkin/Open Tracing in echo-contrib. Can you look at it and close this issue? 

cc: @jcchavezs

**Comment by uudashr** [comment]
@arun0009  it is for Zipkin. I've been thinking to have OpenTracing. So if we have logic inside, they can use generic API which is opentracing. Not specific to the Jaeger, Zipkin, or other

**Comment by aldas** [comment]
Closing, there is a Echo middleware for OpenTracing https://github.com/opentracing-contrib/echo
