### ISSUE TITLE
NewTracedRequest - nil Body

### ISSUE THREAD

**Issue by Dredouane** [labstack/echo-contrib#44]
https://github.com/labstack/echo-contrib/blob/fd0452527ce01ce8a4801451d351aa093f169b97/jaegertracing/jaegertracing.go#L240

POST requests are sent with a nil body? the body param is not used or I'm missing something?
Thanks

**Comment by arun0009** [comment]
@carlosedp I think this is a bug? @Dredouane feel free to pass the body to the line you referenced and open a PR maybe?

**Comment by m1x0n** [comment]
This bit should fix https://github.com/labstack/echo-contrib/pull/71

**Comment by m1x0n** [comment]
Fixed in https://github.com/labstack/echo-contrib/releases/tag/v0.13.1
