### ISSUE TITLE
Prometheus middleware causes double calling of echo errorHandler

### ISSUE THREAD

**Issue by ju-popov** [labstack/echo-contrib#45]
Hello

I was having problems with prometheus middleware. When there is an error, prometheus middleware is calling error handler once more than needed. I think this row have to be commented

https://github.com/labstack/echo-contrib/blob/master/prometheus/prometheus.go#L374

**Comment by ju-popov** [comment]
No, this is not how this should be fixed, instead don't return error in the end of the function

**Comment by aldas** [comment]
should be handled with https://github.com/labstack/echo-contrib/pull/56
