### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by faabiosr** [labstack/echo-contrib#54]
Hi Team! Recently I discovered that the latest version tagged has been a long time ago, I would like to know when we will have a new tag.

I'm asking because has new features in the repo there are important like the Prometheus labels:

https://github.com/labstack/echo-contrib/blob/master/prometheus/prometheus.go#L55

**Comment by winder** [comment]
Yes, please tag a new version. I would also like to use the Prometheus changes made last year.

**Comment by aldas** [comment]
done, https://github.com/labstack/echo-contrib/releases/tag/v0.10.0
