### ISSUE TITLE
Jaeger Service not shown in Jaeger UI

### ISSUE THREAD

**Issue by delgec** [labstack/echo-contrib#74]
Hello everyone

I'm trying to integrate external services into the app but Jaeger Service not shown in Jaeger UI.

![Screenshot from 2022-03-05 16-13-04](https://user-images.githubusercontent.com/61455673/156884636-bf3cbaa0-c49f-4dc8-a060-63571361df48.png)

Where am I doing wrong? How can I fix it?

Help me please.

Sample app:
https://github.com/delgec/echo-opentelemetry-sample

**Comment by m1x0n** [comment]
Hi @delgec ! Looking at your example I'd suggest few things:
- Expose 6831 port (or even all of them to play https://www.jaegertracing.io/docs/1.35/getting-started/#all-in-one) on your jaeger exec
- Set proper env vars during your echo app run (https://echo.labstack.com/middleware/jaegertracing/#custom-configuration):
```
JAEGER_AGENT_HOST=localhost JAEGER_AGENT_PORT=6831 ./yourapp
```
- It might useful for you to build `docker-compose` file to glue together all services you have in one network (jaeger,prometheus,yourapp)

**Comment by delgec** [comment]
> Hi @delgec ! Looking at your example I'd suggest few things:
> 
>     * Expose 6831 port (or even all of them to play https://www.jaegertracing.io/docs/1.35/getting-started/#all-in-one) on your jaeger exec
> 
>     * Set proper env vars during your echo app run (https://echo.labstack.com/middleware/jaegertracing/#custom-configuration):
> 
> 
> ```
> JAEGER_AGENT_HOST=localhost JAEGER_AGENT_PORT=6831 ./yourapp
> ```
> 
>     * It might useful for you to build `docker-compose` file to glue together all services you have in one network (jaeger,prometheus,yourapp)

Thank you very much
