### ISSUE TITLE
Rework Prometheus middleware configuration

### ISSUE THREAD

**Issue by aldas** [labstack/echo-contrib#80]
instead of `NewPrometheus(subsystem string, skipper middleware.Skipper, customMetricsList ...[]*Metric)` that has configuration as list of arguments we should have single argument that is configuration struct. This way it is easier to add new options.

Current and closed issues related to Prometheus:
https://github.com/labstack/echo-contrib/issues?q=is%3Aissue+prometheus+

(for quick look on titles)
* https://github.com/labstack/echo-contrib/issues/93
* https://github.com/labstack/echo-contrib/issues/88
* https://github.com/labstack/echo-contrib/issues/86
* https://github.com/labstack/echo-contrib/issues/85
* https://github.com/labstack/echo-contrib/issues/84
* https://github.com/labstack/echo-contrib/issues/76
* https://github.com/labstack/echo-contrib/issues/70
* https://github.com/labstack/echo-contrib/issues/64
* https://github.com/labstack/echo-contrib/issues/45
* https://github.com/labstack/echo-contrib/issues/36
* https://github.com/labstack/echo-contrib/issues/31
* https://github.com/labstack/echo-contrib/issues/20

**Comment by aldas** [comment]
`Prometheus` is already that "struct" but with those methods and private fields it also much more. starting servers and stuff like that.  I think there should be clearer separation of configuring Prometheus and running server goroutines / handlers.

**Comment by aldas** [comment]
usual Echo middleware conventions could be seen here https://github.com/labstack/echo/blob/f22ba6725c66896efdef029aaeb3bfc471f171c3/middleware/basic_auth.go#L14 

```go
type BasicAuthConfig struct {
//...
}
```

and mw is created from configs as:
```go
func BasicAuthWithConfig(config BasicAuthConfig) echo.MiddlewareFunc {
//...
}
```

also I strongly suggest making list of old issues/PRs related to Prometheus MW and think have people seem to be needing to configure. 

For example couple days ago there was this https://github.com/labstack/echo/discussions/2419 
I have not investigated this much but this global registering thing seems wrong

> This is because middleware.NewPrometheus() registers metrics into global register here https://github.com/labstack/echo-contrib/blob/b6855c2b7d9745b7db2498623e89cae526b41f57/prometheus/prometheus.go#L381

**Comment by yabberyabber** [comment]
It sounds like we are generally in agreement then. Here's an updated proposal that I think addresses both issues:

```
type PrometheusConfig struct {
    LabelDescriminators map[string]func(echo.Context)string

    Registerer prometheus.Registry
}
func NewPrometheusWithConfig(namespace string, config PrometheusConfig) *Prometheus {
}
```

Then this snippet right here https://github.com/labstack/echo-contrib/blob/b6855c2b7d9745b7db2498623e89cae526b41f57/prometheus/prometheus.go#L381 could access the provided Registerer (or default to prometheus.DefaultRegisterer if none is provided).

**Comment by aldas** [comment]
seems ok.

another thing https://github.com/labstack/echo-contrib/blob/b6855c2b7d9745b7db2498623e89cae526b41f57/prometheus/prometheus.go#L399 This method does too much - registering middleware and setting handler should be 2 distinct actions. If I recall correctly Prometheus could PUSH metrics also - therefore assumption that handler is always needed is not correct. 

I think we should not have that much "automagick" and hidden things. ala `go p.router.Start(p.listenAddress)` is hidden in `SetMetricsPath` method

**Comment by yabberyabber** [comment]
I was just starting to notice this same thing as I was implementing the changes on my side :)  I think that for backwards-compatability, `prometheus.NewPrometeus` will need to do the "automagick" thing and register it. But I can change that contract in `prometheus.NewPrometheusWithConfig` so that we only register it under certain circumstances.

How would you prefer this to work in the `prometheus.NewPrometheusWithConfig` scheme? Would you prefer if we made `p.PrometheusHandler()` public (it's currently private) and relied on the user to do something like this?
```
p := prometheus.NewPrometheusWithConfig(subsystem, &PrometheusConfig{})
p.Use(e)
e.GET("/metrics", p.PrometheusHandler())
```

**Comment by yabberyabber** [comment]
I've just posted a draft PR which handles everything except for the expansive `prometheus.Use` implementation. Let me know what you think

**Comment by aldas** [comment]
I'll look this evening but I was actually thinking of creating new middleware and mark old one deprecated. I that way whoever implements that new mw can start from clean sheet.

**Comment by yabberyabber** [comment]
Maintaining backwards compatibility was a little bit awkward but definitely not impossible. I think the PR as written honors the current behavior while providing a straightforward path to extension.  The only thing I wasn't able to address is the overexpansive `prometheus.Use` which I don't think is a huge issue and which could be solved with the addition of a new `PrometheusConfig.SkipRouteEnrollment` in the future.

**Comment by aldas** [comment]
oolright, I think we can and should do even further than tinkering with existing mw. 

I have created PR for different take what prometheus middleware should be https://github.com/labstack/echo-contrib/pull/94
