### ISSUE TITLE
[prometheus][proposal] custom config for standardMetrics

### ISSUE THREAD

**Issue by w1mvy** [labstack/echo-contrib#84]
Hi, This useful middleware has helped us!

### Issue Description

There are cases where we want to overwrite some buckets values.
For example, set buckets value of "request_duration_seconds" greather than 10 seconds.

How about defining a config and allowing it to be overridden?

I would like to get your opinion this.

```golang
type Config struct {
	OverwriteDefaultMetricsList []OverwriteDefaultMetrics
}

type OverwriteDefaultMetrics struct {
	ID      string    // example "reqDur"
	Buckets []float64 // example []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10, 20, 40, 80}
}

```

### Checklist

- [x] Dependencies installed
- [x] No typos
- [x] Searched existing issues and docs

### Expected behaviour

none

### Actual behaviour

none

### Steps to reproduce

none

### Working code to debug

```go
package main

func main() {
}
```

**Comment by tburschka** [comment]
We need this feature too! Some of the requests to us take longer due to the response times from external partners.

**Comment by aldas** [comment]
closing, new middleware was added with #94

The `echoprometheus` middleware registers the following metrics by default:

* Counter `requests_total`
* Histogram `request_duration_seconds`
* Histogram `response_size_bytes`
* Histogram `request_size_bytes`

You can modify their definition before these metrics are registed with  `CounterOptsFunc` and `HistogramOptsFunc` callbacks

```go
package main

import (
	"errors"
	"github.com/labstack/echo-contrib/echoprometheus"
	"github.com/labstack/echo/v4"
	"github.com/prometheus/client_golang/prometheus"
	"log"
	"net/http"
)

func main() {
	e := echo.New()

	// add middleware with custom labels
	e.Use(echoprometheus.NewMiddlewareWithConfig(echoprometheus.MiddlewareConfig{
		HistogramOptsFunc: func(opts prometheus.HistogramOpts) prometheus.HistogramOpts {
			if opts.Name == "request_duration_seconds" {
				opts.Buckets = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10, 20, 40, 80}
			}
			return opts
		},
		CounterOptsFunc: func(opts prometheus.CounterOpts) prometheus.CounterOpts {
			if opts.Name == "requests_total" {
				opts.ConstLabels = prometheus.Labels{"my_const": "123"}
			}
			return opts
		},
	}))
	e.GET("/metrics", echoprometheus.NewHandler()) // register route where metrics can be scraped

	if err := e.Start(":8080"); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatal(err)
	}
}
```
