### ISSUE TITLE
For Prometheus Default metrics, can we host value across all standard metrics

### ISSUE THREAD

**Issue by ankittiwari-harness** [labstack/echo-contrib#88]
### Issue Description

For all the standard Metrics, there are 3 labels present, However, the 4th Label host is available on one of the metrics

```
echo_request_size_bytes_count{code="200",method="POST",url="/v1/api"} 1200

echo_requests_total{code="200",host="localhost:9090",method="POST",url="/v1/api"} 104

```

Ideally we should add Host label as having host helps in differentiating the same API call across multiple service while scraping these metrics

### Checklist

- [x] Dependencies installed
- [x] No typos
- [x] Searched existing issues and docs

### Working code to debug

```go
package main

func main() {
}
```

**Comment by aldas** [comment]
Probably these lines:

"host" needs to be added as arg
https://github.com/labstack/echo-contrib/blob/30200713aeb8f611f6f72b7ac818282ff400d8ed/prometheus/prometheus.go#L79

and provided here
https://github.com/labstack/echo-contrib/blob/30200713aeb8f611f6f72b7ac818282ff400d8ed/prometheus/prometheus.go#L442-L447

**Comment by ankittiwari-harness** [comment]
Yeah, the changes would be exactly here. 

Here is the PR for this from my fork

https://github.com/labstack/echo-contrib/pull/89

**Comment by aldas** [comment]
NB: path is added to metrics this way:
https://github.com/labstack/echo-contrib/blob/b6855c2b7d9745b7db2498623e89cae526b41f57/prometheus/prometheus.go#L194-L202
